// src/main/frontend-react/src/modules/main/components/CrudForm/CrudForm.tsx
import {
    ECrudViewerInputType,
    ICrudViewerConfiguration,
    ICrudViewerConfigurationField
} from "../../types/CrudViewerConfiguration";
import {useForm} from "react-hook-form";
import React, {useEffect, useMemo} from "react";
import Autocomplete from "../../../common/components/Autocomplete/Autocomplete";
import {isFieldVisibleInForm} from "../../utils/CrudViewer.utils";
import {Dictionary} from "../../../common/types/Dictionary";
import {findByPath} from "../../../common/utils/FindByPath";

interface IProps<T> {
    config: ICrudViewerConfiguration;
    entity?: any;
    onSubmit?: (value: Partial<T>) => unknown
}

function createDefaultValues<T = any>(config: ICrudViewerConfiguration, entity: T): Dictionary {
    const output: Dictionary = {};
    config.fields
        .filter(isFieldVisibleInForm)
        .forEach(i => {
            const path = i.writePath || i.path;
            output[path] = findByPath(entity, i.path);
        })
    return output;
}

export default function CrudForm<T>(props: IProps<T>) {
    const defaultValues: any = useMemo(() => createDefaultValues(props.config, props.entity), [props.entity]);
    const { register, handleSubmit, reset, setValue } = useForm();
    const updateForm = () => {
        Object.entries(defaultValues).forEach(([key, value]) => {
            setValue(key, value);
        });
    }

    // On props.entity change - update form
    useEffect(() => updateForm(), [props.entity]);

    const onSubmit = (data: any) => {
        if (props.onSubmit) props.onSubmit(data);
    }

    const renderInput = (field: ICrudViewerConfigurationField, ref: any): JSX.Element => {
        const path = field.writePath || field.path;
        let input: JSX.Element;
        switch (field.type) {
            case ECrudViewerInputType.Text:
                input = <input name={path} type='text' ref={ref}/>;
                break;
            case ECrudViewerInputType.Autocomplete:
                input = <Autocomplete url={field.params} name={path} ref={ref} onFetch={updateForm}/>;
                break;
            case ECrudViewerInputType.Date:
                input = <input name={path} type='date' ref={ref}/>;
                break;
            case ECrudViewerInputType.Checkbox:
                input = <input name={path} type='checkbox' ref={ref}/>;
                break;
            case ECrudViewerInputType.Color:
                input = <input name={path} type='color' ref={ref}/>;
                break;
            default:
                input = <input name={path} type='text' ref={ref}/>;
        }
        return (
            <label key={path}>
                <span>{field.title}</span>
                {input}
            </label>
        );
    }

    const fields = props.config.fields
        .filter(isFieldVisibleInForm)
        .map(i => renderInput(i, register));

    return (
        <form onSubmit={handleSubmit(onSubmit)}>
            {fields}
            <input type="submit" value='Submit'/>
        </form>
    );
}

// src/main/frontend/src/app/components/crud-form/crud-form.component.ts
import {
  Component,
  ChangeDetectionStrategy,
  Input,
  SimpleChanges,
  OnChanges,
  Output,
  EventEmitter
} from '@angular/core';
import {
  ICrudViewerConfiguration,
  ICrudViewerConfigurationField
} from "../../types/CrudViewerConfiguration";
import {FormBuilder, FormGroup} from "@angular/forms";
import {IFormBuilder} from "@rxweb/types";
import {Dictionary} from "../../types/Dictionary";
import { get } from 'lodash';

@Component({
  selector: 'crud-form',
  templateUrl: './crud-form.component.html',
  styleUrls: ['./crud-form.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class CrudFormComponent<T> implements OnChanges {

  @Input() config: ICrudViewerConfiguration | null = null;
  @Input() entity: T | null = null;
  @Output() submitForm = new EventEmitter();

  configEditableFields: ICrudViewerConfigurationField[] = [];
  formGroup!: FormGroup;

  private formBuilder: IFormBuilder = new FormBuilder();

  ngOnChanges({config, entity}: SimpleChanges) {
    if (config && config.isFirstChange() && this.config) {
      this.processConfig(this.config);
    }
    if (entity) {
      this.processEntity(this.entity);
    }
  }

  onSubmit() {
    const values = this.prepareFormValues(this.formGroup.value);
    this.submitForm.emit(values);
  }

  private processConfig(config: ICrudViewerConfiguration): void {
    this.configEditableFields = config.fields
      .filter(i => !i.readOnly)
      .filter(i => !i.isId)
      .filter(i => i.writePath || !i.path.includes("."));
    this.formGroup = this.formBuilder.group(this.createControlsFromConfigFields(this.configEditableFields));
  }

  private processEntity(entity: T | null) {
    if (!this.formGroup) { return; }
    if (entity) {
      this.configEditableFields.forEach(i => {
        const value = get(entity, i.path);
        this.formGroup.get(i.writePath || i.path)?.setValue(value);
      });
    } else {
      this.formGroup.reset();
    }
  }

  private createControlsFromConfigFields(config: ICrudViewerConfigurationField[]): Dictionary {
    const output: {[key: string]: any} = {};
    config.forEach(i => {
      const value = '';
      const path = i.writePath || i.path;
      if (!path) { return; }
      output[path] = [value];
    });
    return output;
  }

  private prepareFormValues(obj: Dictionary): object {
    Object.entries(obj).forEach(([key, value]) => {
      if (!value) {
        delete obj[key];
      }
    });
    return obj;
  }
}

<form *ngIf="formGroup" [formGroup]="formGroup" (ngSubmit)="onSubmit()">
  <ng-container *ngFor="let field of configEditableFields">
    <label class="label">
      {{ field.title }}
      <input
        *ngIf="field.type === 'TEXT' || !field.type"
        [formControlName]="field.writePath || field.path"
      >
      <input
        *ngIf="field.type === 'COLOR'"
        type="color"
        [formControlName]="field.writePath || field.path"
      >
      <input
        *ngIf="field.type === 'DATE'"
        type="date"
        [formControlName]="field.writePath || field.path"
      >
      <input
        *ngIf="field.type === 'CHECKBOX'"
        type="checkbox"
        [formControlName]="field.writePath || field.path"
      >
      <autocomplete-select
        *ngIf="field.type === 'SELECT'"
        [endpoint]="field.params"
        [formControlName]="field.writePath || field.path"
      ></autocomplete-select>
    </label>
  </ng-container>
  <input type="submit" value="Submit">
</form>
